[project]
name = "rs"
version = "5.0.1"
description = "GHGA Registry Service - a service for ingesting and archiving metadata from data submitters."
dependencies = [
    "typer >= 0.26",
    "ghga-service-commons[api,auth,http] >= 8.0",
    "ghga-event-schemas ~= 13.0",
    "hexkit[akafka,mongodb,opentelemetry] >= 9.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-registry-service"

[project.scripts]
rs = "rs.__main__:cli"
